modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="hellasforms"
version="0.9.937"
displayName="HellasForms"
displayURL="https://discord.gg/ggShyqB92C"
credits="xSasaki_Haise, pg13snipez, xGlitzerschaf"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellasforms]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hellasforms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hellasforms]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.13,)"
    ordering="AFTER"
    side="BOTH"